from Problem import Problem
from src.implementation import build_collection_plan


def solution(p: Problem):
    """
    Function required by the project statement.

    The input p is already generated by the evaluator.
    Do not create a new Problem instance here.

    The returned path has the format:
    [(0, 0), (c1, g1), (c2, g2), ..., (0, 0)]
    """

    return build_collection_plan(p)
